### ISSUE TITLE
OpenSSL::SSL

### ISSUE THREAD

**Issue by ReallReaper** [tamatebako/aibika#12]
Hello, I don't know how to speak English very well, therefore I will try to express myself in the best way, I am trying to make a simple ruby ​​program totally basic that downloads an .exe file and saves it in a folder on the local "C" drive, but I have a problem when trying to make the download request for that file I get this error:
Microsoft Windows [Version 10.0.19042.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hamster\Desktop\culoxd>downloadruby.exe
C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect SYSCALL returned=5 errno=0 peeraddr=162.159. 134.233:443 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/http.rb:1342:in `connect'
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/http.rb:1237:in `start'
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/lib/ruby/3.2.0/net/http.rb:687:in `start'
        from C:/Users/hamster/AppData/Local/Temp/aibABA1.tmp/src/downloadruby.rb:9:in `<main>'

C:\Users\hamster\Desktop\culoxd>
(To all this the file works perfectly in .rb but when passing it to .exe no longer) I would like to know if there is any way to solve this, because the only one that occurred to me is to add this to my code:
require 'openssl' # Add OpenSSL to disable SSL certificate verification
and also:
# Disable verification of SSL certificates
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

**Comment by ronaldtse** [comment]
Thank you @ReallReaper for the report!

@maxirmx could you please help try reproduce and investigate this issue? This might have to do with either missing certificates or an outdated certificate bundle, or the fact Aibika is not relying Windows' for certificate management.

**Comment by maxirmx** [comment]
Hi @ReallReaper 
Thank you for yout question

I will start from a simple program like yours
```
# frozen_string_literal: true

require 'open-uri'

url = 'https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.1.4-1/rubyinstaller-3.1.4-1-x64.exe'
filename = "D:/Projects/rubyinstaller-3.1.4-1-x64.exe"

puts "Downloading #{url} to #{filename} ..."

File.open(filename, "wb") do |file|
    begin
        URI.open(url, "rb") do |url_file|
            file.write(url_file.read)
        end
    rescue OpenURI::HTTPError => e
        puts "OpenURI error: #{e.message}"
    rescue OpenSSL::SSL::SSLError => e
        puts "OpenSSL error: #{e.message}"
    end
end
```

This script works is executed unpacked but gives me an eeror is I run aibika-packaged executable
```
OpenSSL error: SSL_connect returned=1 errno=0 peeraddr=140.82.121.4:443 state=error: certificate verify failed (unable to get local issuer certificate)
```

It happens because the package created by aibika runs in a virtual environment that is separated from my 'normal' environment. My SSL certificates are in the normal environment and openssl gem in aibika package does not not how to find these certificates.

I have two options to fix this issuse:
* deploy my package with certificates in it
* have my program look for local certificates 

Since the objective of packaging is to create a program that does not have external dependencies I will follow the first option
(ti be continued in the next comment)

**Comment by maxirmx** [comment]
Now I want to put certificates inside my package.
Three tasks to do:
* obtain and package certificates
* make my program use them

I will take certificates from  _https://curl.se/ca/cacert.pem_   and put _cacert.pem_ aside of my ruby script and package  them together (_download.rb_ is my Ruby script)
```
 aibika download.rb cacert.pem
```

Unfortunately it is not enough -- openssl configuration  deep inside my program does not know anything about this new certificate file.  So I will do some patching to alter it:
```
# frozen_string_literal: true

require 'net/https'
require 'open-uri'

Net::HTTP.class_eval do
  alias _use_ssl= use_ssl=

  def use_ssl= boolean
    self.ca_file = "#{File.expand_path(File.dirname(__FILE__))}/cacert.pem"
    self.verify_mode = OpenSSL::SSL::VERIFY_PEER
    self._use_ssl = boolean
  end
end

url = 'https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.1.4-1/rubyinstaller-3.1.4-1-x64.exe'
filename = "D:/Projects/rubyinstaller-3.1.4-1-x64.exe"

puts "Downloading #{url} to #{filename} ..."

File.open(filename, "wb") do |file|
    begin
        URI.open(url, "rb") do |url_file|
            file.write(url_file.read)
        end
    rescue OpenURI::HTTPError => e
        puts "OpenURI error: #{e.message}"
    rescue OpenSSL::SSL::SSLError => e
        puts "OpenSSL error: #{e.message}"
    end
end
```

Here  I intercept  evaluation of _Net::HTTP_ class and alter its behavior.
The other option would  be to create _OpenSSL_ configuration (an instance of _OpenSSL::Config_ class) and find a way to pass it through _OpenURI_, _URI_, _Net::HTTP_ down to _OpenSSL_ instance

I hope this explanation helps

**Comment by ronaldtse** [comment]
Thanks @maxirmx ! Could you please help put this in the README and on the blog so others can find it? Thanks!

**Comment by maxirmx** [comment]
Thank you, @ronaldtse 
https://github.com/tamatebako/tamatebako.github.io/pull/27
